In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r"D:\Dataset\Myntra Fasion Clothing.csv")

In [35]:
data.index = data.index + 1
data.head(5)

URL  Product_id   BrandName  \
2  https://www.myntra.com/jeans/roadster/roadster...     2296012    Roadster   
3  https://www.myntra.com/track-pants/locomotive/...    13780156  Locomotive   
4  https://www.myntra.com/shirts/roadster/roadste...    11895958    Roadster   
5  https://www.myntra.com/shapewear/zivame/zivame...     4335679      Zivame   
6  https://www.myntra.com/tshirts/roadster/roadst...    11690882    Roadster   

                Category Individual_category category_by_Gender  \
2            Bottom Wear               Jeans                Men   
3            Bottom Wear         Track Pants                Men   
4                Topwear              Shirts                Men   
5  Lingerie & Sleep Wear           Shapewear              Women   
6                Western             Tshirts              Women   

                                         Description  DiscountPrice (in Rs)  \
2  roadster men navy blue slim fit mid rise clean...                  824.0   
3  locomotive men black  white solid slim fit tra...                  517.0   
4  roadster men navy white  black geometric print...                  629.0   
5  zivame women black saree shapewear zi3023core0...                  893.0   
6  roadster women white solid v neck pure cotton ...                  599.0   

   OriginalPrice (in Rs) DiscountOffer              SizeOption  Ratings  \
2                 1499.0       45% OFF      28, 30, 32, 34, 36      3.9   
3                 1149.0       55% OFF          36, 38, 40, 40      4.0   
4                 1399.0       55% OFF  38, 40, 42, 44, 46, 48      4.3   
5                 1295.0       31% OFF      36, 38, 40, 40, 40      4.2   
6                  599.0       35% OFF      36, 36, 38, 40, 40      4.2   

   Reviews  
2    999.0  
3    999.0  
4    999.0  
5    999.0  
6    999.0

In [4]:
data.dtypes

URL                       object
Product_id                 int64
BrandName                 object
Category                  object
Individual_category       object
category_by_Gender        object
Description               object
DiscountPrice (in Rs)    float64
OriginalPrice (in Rs)    float64
DiscountOffer             object
SizeOption                object
Ratings                  float64
Reviews                  float64
dtype: object

## Remove Missing Values

In [5]:
missing_values = data.isnull().sum()
missing_values

URL                           0
Product_id                    0
BrandName                     0
Category                      0
Individual_category           0
category_by_Gender            0
Description                   0
DiscountPrice (in Rs)    193158
OriginalPrice (in Rs)         0
DiscountOffer             74306
SizeOption                    0
Ratings                  336152
Reviews                  336152
dtype: int64

In [6]:
data['DiscountPrice (in Rs)'].fillna(data['OriginalPrice (in Rs)'], inplace=True)

In [7]:
data['DiscountOffer'].fillna('No Discount', inplace=True)

In [8]:
data['Reviews'].fillna(0, inplace=True)

In [9]:
data['Ratings'].fillna(0, inplace=True)

## Checking Duplicates

In [10]:
duplicates = data.duplicated().sum()
duplicates

np.int64(0)

## checking unique values

In [11]:
data["URL"].unique()

array(['https://www.myntra.com/jeans/roadster/roadster-men-navy-blue-slim-fit-mid-rise-clean-look-jeans/2296012/buy',
       'https://www.myntra.com/track-pants/locomotive/locomotive-men-black--white-solid-slim-fit-track-pants/13780156/buy',
       'https://www.myntra.com/shirts/roadster/roadster-men-navy-white--black-geometric-printed-sustainable-casual-shirt/11895958/buy',
       ...,
       'https://www.myntra.com/dresses/250-designs/250-designs-blue-lace-sheath-dress/17654114/buy',
       'https://www.myntra.com/dresses/masaba/masaba-women-yellow-printed-a-line-dress/12508700/buy',
       'https://www.myntra.com/tshirts/jockey/jockey-women-blue-extended-sleeves-t-shirt/17856544/buy'],
      dtype=object)

In [12]:
data["Product_id"].unique()

array([ 2296012, 13780156, 11895958, ..., 17654114, 12508700, 17856544])

In [13]:
data["BrandName"].unique()

array(['Roadster', 'LOCOMOTIVE', 'Zivame', ..., 'Doodlage', 'CHOZI',
       'STATUS MANTRA'], dtype=object)

In [14]:
data['BrandName'] = data['BrandName'].str.title()

In [15]:
data["Category"].unique()

array(['Bottom Wear', 'Topwear', 'Lingerie & Sleep Wear', 'Western',
       'Sports Wear', 'Indian Wear', 'Plus Size',
       'Inner Wear &  Sleep Wear'], dtype=object)

In [16]:
data["Individual_category"].unique()

array(['jeans', 'track-pants', 'shirts', 'shapewear', 'tshirts', 'tops',
       'trousers', 'tights', 'kurta-sets', 'jumpsuit', 'kurtas', 'bra',
       'shorts', 'dresses', 'bath-robe', 'jackets', 'socks', 'briefs',
       'sweatshirts', 'sarees', 'trunk', 'kurtis', 'skirts',
       'night-suits', 'lounge-pants', 'palazzos', 'stockings', 'jeggings',
       'leggings', 'shrug', 'boxers', 'dupatta', 'tunics',
       'innerwear-vests', 'sweaters', 'lounge-shorts', 'thermal-tops',
       'capris', 'nightdress', 'pyjamas', 'sports-sandals', 'dungarees',
       'tracksuits', 'camisoles', 'nehru-jackets', 'blazers',
       'thermal-bottoms', 'lounge-tshirts', 'lehenga-choli', 'baby-dolls',
       'coats', 'thermal-set', 'saree-blouse', 'churidar',
       'dress-material', 'boots', 'lingerie-set', 'sherwani', 'co-ords',
       'flats', 'swimwear', 'rain-jacket', 'patiala', 'salwar',
       'harem-pants', 'patiala-and-dupatta', 'lingerie-accessories',
       'saree-accessories', 'suits', 'dhoti

In [17]:
data['Individual_category'] = data['Individual_category'].str.replace("-"," ")

In [18]:
data['Individual_category'] = data['Individual_category'].str.title()

In [19]:
data["category_by_Gender"].unique()

array(['Men', 'Women'], dtype=object)

In [20]:
data["Description"].unique()

array(['roadster men navy blue slim fit mid rise clean look jeans',
       'locomotive men black  white solid slim fit track pants',
       'roadster men navy white  black geometric printed sustainable casual shirt',
       ..., '250 designs blue lace sheath dress',
       'masaba women yellow printed a line dress',
       'jockey women blue extended sleeves t shirt'], dtype=object)

In [21]:
data["DiscountPrice (in Rs)"].unique()

array([ 824.,  517.,  629., ..., 5775., 8300., 8440.])

In [22]:
data["OriginalPrice (in Rs)"].unique()

array([1499., 1149., 1399., ..., 6276., 7992., 9592.])

In [23]:
data["DiscountOffer"].unique()

array(['45% OFF', '55% OFF', '31% OFF', ..., 'Rs. 334 OFF', 'Rs. 375 OFF',
       'Rs. 283 OFF'], dtype=object)

In [24]:
def convert_discount(value, original_price):
    if 'Rs.' in value:
        rs_off = int(value.split()[1])
        percent_off = (rs_off / original_price) * 100
        return f"{round(percent_off)}% OFF"
    else:
        return value
data['DiscountOffer'] = data.apply(lambda row: convert_discount(row['DiscountOffer'], row['OriginalPrice (in Rs)']), axis=1)

In [25]:
data['DiscountOffer'] = data['DiscountOffer'].str.replace("Hurry*","60% OFF")

In [33]:
data["SizeOption"].unique()

array(['28, 30, 32, 34, 36', '36, 38, 40, 40', '38, 40, 42, 44, 46, 48',
       ..., '32, 34, 36, 38, 40, 44, 42, 46', '6, 10, 8, 14, 12, 18, 16',
       '26, 27, 28, 29, 30, 32'], dtype=object)

In [32]:
data['SizeOption'] = data['SizeOption'].str.replace("S","36")
data['SizeOption'] = data['SizeOption'].str.replace("M","38")
data['SizeOption'] = data['SizeOption'].str.replace("L","40")
data['SizeOption'] = data['SizeOption'].str.replace("X","")

In [36]:
data["Ratings"].unique()

array([3.9, 4. , 4.3, 4.2, 4.4, 3.7, 3.5, 4.1, 3.8, 3.6, 4.5, 4.6, 3.4,
       3.2, 4.7, 3.3, 3. , 3.1, 2.9, 2.8, 2.6, 2.5, 2.4, 2. , 2.7, 4.8,
       4.9, 2.3, 1.6, 2.2, 2.1, 1.8, 5. , 1.2, 1.9, 1.7, 1.4, 1.5, 1.1,
       1. , 1.3, 0. ])

In [37]:
data["Reviews"].unique()

array([999., 998., 997., 996., 995., 994., 993., 992., 991., 990., 989.,
       988., 987., 986., 985., 984., 983., 982., 981., 980., 979., 978.,
       977., 976., 975., 974., 973., 972., 971., 970., 969., 968., 967.,
       966., 965., 964., 963., 962., 961., 960., 959., 958., 957., 956.,
       955., 954., 953., 952., 951., 950., 949., 948., 947., 946., 945.,
       944., 943., 942., 941., 940., 939., 938., 937., 936., 935., 934.,
       933., 932., 931., 930., 929., 928., 927., 926., 925., 924., 923.,
       922., 921., 920., 919., 918., 917., 916., 915., 914., 913., 912.,
       911., 910., 909., 908., 907., 906., 905., 904., 903., 902., 901.,
       900., 899., 898., 897., 896., 895., 894., 893., 892., 891., 890.,
       889., 888., 887., 886., 885., 884., 883., 882., 881., 880., 879.,
       878., 877., 876., 875., 874., 873., 872., 871., 870., 869., 868.,
       867., 866., 865., 864., 863., 862., 861., 860., 859., 858., 857.,
       856., 855., 854., 853., 852., 851., 850., 84

In [38]:
data.to_csv('myntra_clean_data.csv', index=False)
 